### ISSUE TITLE
Can't install Express Forms

### ISSUE THREAD

**Issue by bartrylant** [solspace/craft-express-forms#29] opened 2020-01-16 15:06 UTC
When trying to install Express Forms through the CLI, I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ramsey/uuid (locked at 3.9.2) -> satisfiable by ramsey/uuid[3.9.2].
    - solspace/craft-express-forms 1.0.0 requires ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].
    - solspace/craft-express-forms 1.0.1 requires ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].
    - solspace/craft-express-forms 1.0.2 requires ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].
    - solspace/craft-express-forms 1.0.3 requires ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].
    - solspace/craft-express-forms 1.0.4 requires ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].
    - Conclusion: don't install ramsey/uuid 3.8.0
    - Installation request for solspace/craft-express-forms ^1.0 -> satisfiable by solspace/craft-express-forms[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].

Installation failed, reverting ./composer.json to its original content.
```

PHP version 7.3.8
MySQL 5.7.26
Imagick 3.4.3 (ImageMagick 6.9.6-2)
Craft Pro 3.3.20.1

**Comment by tyssen** [comment] 2020-01-20 06:02
Yep, same here.

**Comment by bartrylant** [comment] 2020-01-30 16:03
Any news?

**Comment by kjmartens** [comment] 2020-02-11 19:56
Sorry for the delay on this one. This will be fixed for Express Forms 1.0.5, available this week (possibly today). :)

**Comment by avr** [comment] 2020-05-03 01:13
This is still broken. I think it would be fixed if you can update your componser.json to use:

`"ramsey/uuid": "^3.0|^4.0",`

Thanks!

**Comment by clarknelson** [comment] 2020-12-15 20:33
Running into the same issue
![image](https://user-images.githubusercontent.com/4106671/102269571-7320ea00-3ee2-11eb-8b7d-c8f402075087.png)

**Comment by gustavs-gutmanis** [comment] 2020-12-15 21:01
@clarknelson could you please paste your `composer.json` file contents here?  
I'll try ND reproduce the issue.  
Thanks

**Comment by clarknelson** [comment] 2020-12-15 21:34
```
{
  "name": ".../...",
  "description": "Craft CMS",
  "keywords": [
    "craft",
    "cms",
    "craftcms",
    "project"
  ],
  "license": "proprietary",
  "homepage": "https://craftcms.com/",
  "type": "project",
  "support": {
    "email": "support@craftcms.com",
    "issues": "https://github.com/craftcms/cms/issues",
    "forum": "https://craftcms.stackexchange.com/",
    "source": "https://github.com/craftcms/cms",
    "docs": "https://craftcms.com/docs",
    "rss": "https://craftcms.com/changelog.rss"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "clarknelson/craft-recaptcha-3": "^1.1",
    "craftcms/cms": "^3.0.31",
    "craftcms/element-api": "^2.5.4",
    "craftcms/feed-me": "^4.1",
    "craftcms/redactor": "^2.1.6",
    "doublesecretagency/craft-cpcss": "^2.1.0",
    "ether/logs": "^3.0",x
    "ether/splash": "^3.0.2",
    "nystudio107/craft-cookies": "^1.1.10",
    "nystudio107/craft-retour": "^3.0.18",
    "nystudio107/craft-seomatic": "^3.1.36",
    "nystudio107/craft-typogrify": "^1.1",
    "nystudio107/craft-webperf": "^1.0.1",
    "studioespresso/craft-dumper": "^1.3",
    "verbb/expanded-singles": "^1.0.5",
    "verbb/field-manager": "^2.0.4",
    "verbb/super-table": "^2.0.10",
    "vlucas/phpdotenv": "^2.4.0",
    "wbrowar/guide": "2.1.3.3",
    "wbrowar/adminbar": "^3.1",
    "nav33d/craft-activitylog": "^1.0",
    "spicyweb/craft-neo": "2.8.15.1",
    "paragonie/random_compat": "^9.99",
    "solspace/craft-express-forms": "1.0.8"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-create-project-cmd": [
      "@php -r \"copy('.env.example', '.env');\"",
      "@php -r \"unlink('composer.json');\"",
      "@php -r \"unlink('LICENSE.md');\"",
      "@php -r \"unlink('README.md');\"",
      "@php -r \"rename('composer.json.default', 'composer.json');\"",
      "@composer dump-autoload -o",
      "@php craft setup/welcome"
    ]
  }
}
```

**Comment by clarknelson** [comment] 2020-12-15 21:34
I was able to install using the control panel as mentioned in the other issue

**Comment by gustavs-gutmanis** [comment] 2020-12-16 10:13
Turns out that the `ramsey/uuid` package is fixed on using the exact `paragonie/random_compat` package `v9.99.99`, but the latest they have is `v9.99.100`.  
I checked it out and the only version of `ramsey/uuid` package which doesn't require that version is the `v4.x`, but it requires PHP 7.2+, thus requiring it wouldn't solve the issue for people using older versions of PHP.

To fix this, I set the `paragonie/random_compat` requirement to a strict `9.99.99` and did `composer update` and then I did `composer require solspace/craft-express-forms` and it worked.

Could you see if that works for you @clarknelson, @tyssen, @bartrylant?  

To re-iterate:
* Remove the `"solspace/craft-express-forms": "1.0.8"` requirement from your `composer.json`
* Set the `"paragonie/random_compat": "^9.99"` to `"paragonie/random_compat": "9.99.99"`
* Do `composer update`
* Do `composer require solspace/craft-express-forms`

**Comment by clarknelson** [comment] 2020-12-16 14:52
that worked for me I believe

**Closed** 2020-12-17 14:33 UTC
Labels: bug
